"""expand transaction model

Revision ID: bdd2897860e3
Revises: 
Create Date: 2026-06-02 12:25:29.338534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd2897860e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('lead_source', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mls_live_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('expiry_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('under_contract_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('projected_close_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('list_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bonus', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('transaction_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('broker_split', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('franchise_split', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('referral_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('taxes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('net_after_taxes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('primary_agent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('primary_agent_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('primary_agent_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('primary_agent_gci', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('secondary_agent_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('secondary_agent_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('secondary_agent_gci', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mortgage_company', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('title_company', sa.String(length=100), nullable=True))
        batch_op.alter_column('agent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('client_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'agents', ['primary_agent_id'], ['id'])
        batch_op.drop_column('contract_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_date', sa.DATE(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('client_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('agent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('title_company')
        batch_op.drop_column('mortgage_company')
        batch_op.drop_column('secondary_agent_gci')
        batch_op.drop_column('secondary_agent_pct')
        batch_op.drop_column('secondary_agent_name')
        batch_op.drop_column('primary_agent_gci')
        batch_op.drop_column('primary_agent_pct')
        batch_op.drop_column('primary_agent_name')
        batch_op.drop_column('primary_agent_id')
        batch_op.drop_column('net_after_taxes')
        batch_op.drop_column('taxes')
        batch_op.drop_column('referral_fee')
        batch_op.drop_column('franchise_split')
        batch_op.drop_column('broker_split')
        batch_op.drop_column('transaction_fee')
        batch_op.drop_column('bonus')
        batch_op.drop_column('list_price')
        batch_op.drop_column('projected_close_date')
        batch_op.drop_column('under_contract_date')
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('mls_live_date')
        batch_op.drop_column('location')
        batch_op.drop_column('lead_source')
        batch_op.drop_column('sub_status')

    # ### end Alembic commands ###
